In [2]:
import numpy as numpy

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('cities.csv')

In [5]:
df.shape

(508, 27)

In [6]:
df.columns

Index(['city_id', 'city', 'state', 'country', 'continent', 'population',
       'area_km2', 'population_density', 'internet_pct',
       'electricity_access_pct', 'unemployment_pct', 'literacy_pct',
       'median_age', 'annual_rainfall_mm', 'avg_temperature_c',
       'air_quality_index', 'hospitals', 'schools', 'crime_rate',
       'green_space_pct', 'public_transport_pct', 'tourism_index',
       'cost_of_living_index', 'avg_income_usd', 'city_score', 'developed',
       'population_density_check'],
      dtype='str')

In [7]:
df["unemployment_pct"]

0       2.84
1       5.35
2       6.04
3       4.73
4        1.0
       ...
503     12.1
504     8.17
505    12.51
506     2.67
507     3.64
Name: unemployment_pct, Length: 508, dtype: str

In [8]:
df.describe()

,city_id,population,area_km2,internet_pct,electricity_access_pct,literacy_pct,median_age,annual_rainfall_mm,air_quality_index,hospitals,schools,crime_rate,green_space_pct,public_transport_pct,tourism_index,cost_of_living_index,avg_income_usd,city_score,developed,population_density_check
count,508.000000,5.080000e+02,508.000000,496.000000,498.000000,493.000000,508.000000,508.000000,493.000000,508.000000,508.000000,508.000000,508.000000,508.000000,498.000000,508.000000,495.000000,508.000000,508.000000,5.080000e+02
mean,250.433071,3.834371e+06,174.759685,77.312056,88.591365,82.419493,34.091535,135.717697,86.097363,89.653543,250.673228,39.966457,30.680827,54.397047,53.808112,53.986181,34534.260949,62.065217,0.500000,3.808738e+04
std,144.311565,4.434692e+07,217.507115,14.447317,8.832987,9.741265,5.793132,78.640259,34.218502,9.759941,16.539222,45.099202,14.128421,22.895731,24.366600,19.902334,19297.534080,6.387353,0.500493,2.674245e+05
min,1.000000,1.200000e+02,20.000000,33.670000,60.520000,53.380000,18.000000,12.000000,10.000000,58.000000,197.000000,-5.000000,2.000000,5.000000,1.000000,15.000000,5395.070000,41.740000,0.000000,7.420233e-01
25%,125.000000,5.694858e+05,56.432500,67.885000,82.972500,75.660000,30.100000,78.210000,60.600000,83.000000,240.000000,27.562500,21.557500,38.600000,37.070000,40.517500,20838.890000,57.375000,0.000000,4.350929e+03
50%,250.500000,1.188018e+06,111.270000,78.030000,89.530000,82.240000,34.200000,120.840000,85.600000,89.000000,251.000000,37.820000,30.505000,53.795000,53.485000,53.920000,29548.410000,62.210000,0.500000,1.039494e+04
75%,375.250000,2.151103e+06,199.415000,87.805000,95.965000,89.700000,38.125000,168.725000,111.300000,96.000000,261.000000,47.557500,40.030000,71.525000,71.337500,66.540000,43938.415000,66.392500,1.000000,2.616057e+04
max,500.000000,1.000000e+09,2026.090000,100.000000,100.000000,100.000000,52.500000,556.580000,198.400000,125.000000,308.000000,999.000000,71.300000,100.000000,100.000000,116.290000,150000.000000,81.330000,1.000000,5.929088e+06

In [9]:
df.head()

,city_id,city,state,country,continent,population,area_km2,population_density,internet_pct,electricity_access_pct,...,schools,crime_rate,green_space_pct,public_transport_pct,tourism_index,cost_of_living_index,avg_income_usd,city_score,developed,population_density_check
0,80,Asyut,Asyut Governorate,Egypt,Africa,1729692,80.69,21435.43,99.53,94.46,...,253,55.88,49.13,29.54,76.73,46.39,32398.78,66.47,1,21436.262238
1,317,Tabuk,Tabuk Province,Saudi Arabia,Asia,804525,117.51,6846.29,74.96,97.64,...,243,48.63,36.83,5.00,5.83,57.72,20173.67,48.52,0,6846.438601
2,486,Johor Bahru,Johor,Malaysia,Asia,2262501,92.72,24401.23,65.86,88.10,...,230,20.32,36.48,38.63,100.00,45.75,26500.75,65.06,1,24401.434426
3,397,Namur,Wallonia,Belgium,Europe,611691,235.13,2601.52,87.04,75.49,...,237,35.35,52.05,51.04,95.48,75.40,47391.13,72.61,1,2601.501297
4,168,Strasbourg,Grand Est,France,Europe,1947519,161.57,12053.57,100.00,91.02,...,242,25.55,33.49,74.67,49.33,36.20,16295.54,72.01,1,12053.716655

In [10]:
df.head(2)

,city_id,city,state,country,continent,population,area_km2,population_density,internet_pct,electricity_access_pct,...,schools,crime_rate,green_space_pct,public_transport_pct,tourism_index,cost_of_living_index,avg_income_usd,city_score,developed,population_density_check
0,80,Asyut,Asyut Governorate,Egypt,Africa,1729692,80.69,21435.43,99.53,94.46,...,253,55.88,49.13,29.54,76.73,46.39,32398.78,66.47,1,21436.262238
1,317,Tabuk,Tabuk Province,Saudi Arabia,Asia,804525,117.51,6846.29,74.96,97.64,...,243,48.63,36.83,5.00,5.83,57.72,20173.67,48.52,0,6846.438601

In [11]:
df.tail()

,city_id,city,state,country,continent,population,area_km2,population_density,internet_pct,electricity_access_pct,...,schools,crime_rate,green_space_pct,public_transport_pct,tourism_index,cost_of_living_index,avg_income_usd,city_score,developed,population_density_check
503,107,Palembang,South Sumatra,Indonesia,Asia,2579036,42.52,60654.45,57.66,96.08,...,238,22.38,25.52,65.14,40.78,17.22,19306.30,58.84,0,60654.656632
504,271,Bogotá,Bogotá D.C.,Colombia,South America,6776662,53.43,126823.7,100.00,86.49,...,261,47.22,25.14,31.43,78.72,44.21,43369.58,72.28,1,126832.528542
505,349,Breda,North Brabant,Netherlands,Europe,592872,22.61,26221.32,91.74,87.15,...,260,58.06,29.11,58.50,57.71,20.61,24564.10,65.84,1,26221.671827
506,436,Fredrikstad,Østfold,Norway,Europe,2168501,60.04,36118.03,76.75,100.00,...,271,47.01,15.79,43.03,69.48,47.28,NaN,61.74,0,36117.604930
507,103,Bandung,West Java,Indonesia,Asia,4301383,76.99,55865.99,86.98,100.00,...,197,38.20,56.97,75.74,23.83,64.13,28524.76,69.53,1,55869.372646

In [12]:
df.tail(10)

,city_id,city,state,country,continent,population,area_km2,population_density,internet_pct,electricity_access_pct,...,schools,crime_rate,green_space_pct,public_transport_pct,tourism_index,cost_of_living_index,avg_income_usd,city_score,developed,population_density_check
498,122,Kano,Kano State,Nigeria,Africa,1241843,131.54,9441.14,78.05,91.47,...,218,31.83,3.12,60.76,38.08,34.15,34889.70,60.14,0,9440.801277
499,125,Port Harcourt,Rivers State,Nigeria,Africa,1926347,253.44,7600.92,75.24,92.92,...,260,49.39,58.85,37.43,61.28,85.16,NaN,66.54,1,7600.800979
500,21,Shanghai,Shanghai,China,Asia,455818,91.39,4987.61,83.10,78.32,...,262,21.37,25.39,17.01,82.59,59.84,63818.37,62.76,1,4987.613524
501,189,Bari,Apulia,Italy,Europe,760065,27.99,27155.05,87.19,89.59,...,230,41.01,33.96,90.01,23.04,34.56,14775.10,64.31,1,27154.876742
502,72,Alexandria,Alexandria Governorate,Egypt,Africa,1123567,35.40,31739.15,61.28,88.80,...,273,48.10,26.72,59.49,72.66,28.08,61491.47,63.27,1,31739.180791
503,107,Palembang,South Sumatra,Indonesia,Asia,2579036,42.52,60654.45,57.66,96.08,...,238,22.38,25.52,65.14,40.78,17.22,19306.30,58.84,0,60654.656632
504,271,Bogotá,Bogotá D.C.,Colombia,South America,6776662,53.43,126823.7,100.00,86.49,...,261,47.22,25.14,31.43,78.72,44.21,43369.58,72.28,1,126832.528542
505,349,Breda,North Brabant,Netherlands,Europe,592872,22.61,26221.32,91.74,87.15,...,260,58.06,29.11,58.50,57.71,20.61,24564.10,65.84,1,26221.671827
506,436,Fredrikstad,Østfold,Norway,Europe,2168501,60.04,36118.03,76.75,100.00,...,271,47.01,15.79,43.03,69.48,47.28,NaN,61.74,0,36117.604930
507,103,Bandung,West Java,Indonesia,Asia,4301383,76.99,55865.99,86.98,100.00,...,197,38.20,56.97,75.74,23.83,64.13,28524.76,69.53,1,55869.372646

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   city_id                   508 non-null    int64
 1   city                      508 non-null    str
 2   state                     508 non-null    str
 3   country                   508 non-null    str
 4   continent                 508 non-null    str
 5   population                508 non-null    int64
 6   area_km2                  508 non-null    float64
 7   population_density        507 non-null    str
 8   internet_pct              496 non-null    float64
 9   electricity_access_pct    498 non-null    float64
 10  unemployment_pct          507 non-null    str
 11  literacy_pct              493 non-null    float64
 12  median_age                508 non-null    float64
 13  annual_rainfall_mm        508 non-null    float64
 14  avg_temperature_c         507 non-null    str
 15  air_quality_index         493 non-null    float64
 16  hospitals                 508 non-null    int64
 17  schools                   508 non-null    int64
 18  crime_rate                508 non-null    float64
 19  green_space_pct           508 non-null    float64
 20  public_transport_pct      508 non-null    float64
 21  tourism_index             498 non-null    float64
 22  cost_of_living_index      508 non-null    float64
 23  avg_income_usd            495 non-null    float64
 24  city_score                508 non-null    float64
 25  developed                 508 non-null    int64
 26  population_density_check  508 non-null    float64
dtypes: float64(15), int64(5), str(7)
memory usage: 131.1 KB

In [14]:
df["population_density"]

0      21435.43
1       6846.29
2      24401.23
3       2601.52
4      12053.57
         ...
503    60654.45
504    126823.7
505    26221.32
506    36118.03
507    55865.99
Name: population_density, Length: 508, dtype: str

In [15]:
df["population_density"][0]

'21435.43'

In [16]:
#What are the top 5 most populated cities?


df[df["population"]==df["population"].max()]

,city_id,city,state,country,continent,population,area_km2,population_density,internet_pct,electricity_access_pct,...,schools,crime_rate,green_space_pct,public_transport_pct,tourism_index,cost_of_living_index,avg_income_usd,city_score,developed,population_density_check
86,440,Ålesund,Møre og Romsdal,Norway,Europe,999999999,168.66,16950.93,94.81,82.98,...,259,54.59,42.17,14.0,40.29,39.67,29548.41,57.69,0,5.929088e+06

In [17]:
#which city has the higest population ?

df[df["population"]==df["population"].max()]["city"]

86    Ålesund
Name: city, dtype: str

In [18]:
#which city has the lowest population ?

df[df["population"]==df["population"].min()]["city"]

33    Cúcuta
Name: city, dtype: str

In [19]:
#which country contains the city with the highest population?

df[df["population"]==df["population"].max()]["country"]

86    Norway
Name: country, dtype: str

In [32]:
#which state/region contains the most populated city?

df[df["population"]==df["population"].max()]["state"]

86    Møre og Romsdal
Name: state, dtype: str

In [20]:
#which city has highest internetpct

df[df["internet_pct"]==df["internet_pct"].max()]["city"]

4         Strasbourg
19              León
28            Tehran
35          Hamilton
63           Horsens
66          Mansoura
80          Zaragoza
91            Rhodes
106     Thessaloniki
115          Antwerp
123           Ashdod
132           Málaga
134        Maiduguri
154          Porirua
167           Moscow
178          Leipzig
220        Jyväskylä
229          Pereira
257           Bilbao
266           Quetta
268           Goyang
271           Poznań
283             Oulu
293       Lower Hutt
306          Kolding
310    Buon Ma Thuot
331          Pattaya
376           Bruges
380            Arica
396      Biel/Bienne
409            Hanoi
420           Madrid
424           Puebla
442        Groningen
446             Taif
450      Montpellier
494            Lahti
504           Bogotá
Name: city, dtype: str

In [21]:
df[df["internet_pct"]==df["internet_pct"].min()]["city"]

402    Sandnes
Name: city, dtype: str

In [22]:
df[df["internet_pct"]==df["internet_pct"].max()]["city"].count()

np.int64(38)

In [23]:
df[df["internet_pct"]==df["internet_pct"].min()]["city"].count()

np.int64(1)

In [24]:
#city with highest electricity 

df[df["electricity_access_pct"]==df["electricity_access_pct"].max()]["city"]

5         Tampines
30        Roskilde
35        Hamilton
37      St. Gallen
41           Plzeň
          ...
485      Nha Trang
489        Hamburg
493        Comilla
506    Fredrikstad
507        Bandung
Name: city, Length: 71, dtype: str

In [25]:
df[df["electricity_access_pct"]==df["electricity_access_pct"].max()]["city"].count()

np.int64(71)

In [26]:
df[df["electricity_access_pct"]==df["electricity_access_pct"].min()]["city"]

45    Volos
Name: city, dtype: str

In [27]:
df.sort_values(by="population",ascending=False)[["city","country","population"]].head()

          city         country  population
86     Ålesund          Norway   999999999
341    Tilburg     Netherlands    28885597
12      Ankara          Turkey    15391530
241    Kolkata           India    13529932
87   Sheffield  United Kingdom    13027880

In [28]:
df.sort_values(by="population")[["city","country","population"]].head()

          city   country  population
33      Cúcuta  Colombia         120
30    Roskilde   Denmark       50000
356  Ahmedabad     India       62036
63     Horsens   Denmark       64177
323      Kalba       UAE       83047

In [29]:
df.sort_values(by="population_density")[["city","country","population_density"]].head()

              city     country population_density
109     Mymensingh  Bangladesh
232         Mersin      Turkey            1002.89
150     Udon Thani    Thailand          100534.94
344    Guadalajara      Mexico           10150.16
169  Mar del Plata   Argentina           10180.11