In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('cities.csv')

In [4]:
df.info

<bound method DataFrame.info of      city_id         city              state       country      continent  \
0         80        Asyut  Asyut Governorate         Egypt         Africa
1        317        Tabuk     Tabuk Province  Saudi Arabia           Asia
2        486  Johor Bahru              Johor      Malaysia           Asia
3        397        Namur           Wallonia       Belgium         Europe
4        168   Strasbourg          Grand Est        France         Europe
..       ...          ...                ...           ...            ...
503      107    Palembang      South Sumatra     Indonesia           Asia
504      271       Bogotá        Bogotá D.C.      Colombia  South America
505      349        Breda      North Brabant   Netherlands         Europe
506      436  Fredrikstad            Østfold        Norway         Europe
507      103      Bandung          West Java     Indonesia           Asia

     population  area_km2 population_density  internet_pct  \
0       1729692     80.69           21435.43         99.53
1        804525    117.51            6846.29         74.96
2       2262501     92.72           24401.23         65.86
3        611691    235.13            2601.52         87.04
4       1947519    161.57           12053.57        100.00
..          ...       ...                ...           ...
503     2579036     42.52           60654.45         57.66
504     6776662     53.43           126823.7        100.00
505      592872     22.61           26221.32         91.74
506     2168501     60.04           36118.03         76.75
507     4301383     76.99           55865.99         86.98

     electricity_access_pct  ... schools  crime_rate  green_space_pct  \
0                     94.46  ...     253       55.88            49.13
1                     97.64  ...     243       48.63            36.83
2                     88.10  ...     230       20.32            36.48
3                     75.49  ...     237       35.35            52.05
4                     91.02  ...     242       25.55            33.49
..                      ...  ...     ...         ...              ...
503                   96.08  ...     238       22.38            25.52
504                   86.49  ...     261       47.22            25.14
505                   87.15  ...     260       58.06            29.11
506                  100.00  ...     271       47.01            15.79
507                  100.00  ...     197       38.20            56.97

     public_transport_pct tourism_index  cost_of_living_index  avg_income_usd  \
0                   29.54         76.73                 46.39        32398.78
1                    5.00          5.83                 57.72        20173.67
2                   38.63        100.00                 45.75        26500.75
3                   51.04         95.48                 75.40        47391.13
4                   74.67         49.33                 36.20        16295.54
..                    ...           ...                   ...             ...
503                 65.14         40.78                 17.22        19306.30
504                 31.43         78.72                 44.21        43369.58
505                 58.50         57.71                 20.61        24564.10
506                 43.03         69.48                 47.28             NaN
507                 75.74         23.83                 64.13        28524.76

     city_score  developed  population_density_check
0         66.47          1              21436.262238
1         48.52          0               6846.438601
2         65.06          1              24401.434426
3         72.61          1               2601.501297
4         72.01          1              12053.716655
..          ...        ...                       ...
503       58.84          0              60654.656632
504       72.28          1             126832.528542
505       65.84          1              26221.671827
506       61.74          0              36117.604930
507       69.53          1              55869.372646

[508 rows x 27 columns]>

In [5]:
df.columns

Index(['city_id', 'city', 'state', 'country', 'continent', 'population',
       'area_km2', 'population_density', 'internet_pct',
       'electricity_access_pct', 'unemployment_pct', 'literacy_pct',
       'median_age', 'annual_rainfall_mm', 'avg_temperature_c',
       'air_quality_index', 'hospitals', 'schools', 'crime_rate',
       'green_space_pct', 'public_transport_pct', 'tourism_index',
       'cost_of_living_index', 'avg_income_usd', 'city_score', 'developed',
       'population_density_check'],
      dtype='str')

In [6]:
# 1.Which city has the highest population ?

df[df['population']==df['population'].max()]['city']

86    Ålesund
Name: city, dtype: str

In [7]:
# 2.Which city has  the lowest population ?

df[df['population']==df['population'].min()]['city']

33    Cúcuta
Name: city, dtype: str

In [8]:
# 3.Which country contains the city with highest population ?

df[df['population']==df['population'].max()]['country']

86    Norway
Name: country, dtype: str

In [9]:
# 4.Which state /region contains the most population ?

df[df['population']==df['population'].max()]['state']

86    Møre og Romsdal
Name: state, dtype: str

In [10]:
df.state

0      Asyut Governorate
1         Tabuk Province
2                  Johor
3               Wallonia
4              Grand Est
             ...
503        South Sumatra
504          Bogotá D.C.
505        North Brabant
506              Østfold
507            West Java
Name: state, Length: 508, dtype: str

In [11]:
# 5.Who is the mayor of most popular city ?

#df[df['population']==df['population'].max()]['mayor']

In [12]:
# 6. What is area of most populated city ?

# df[df['population']==pd['population'].max()]['area_km2']

In [13]:
# 7.what is the population density of the most populated city ?

df[df['population']==df['population'].max()]['population_density']

86    16950.93
Name: population_density, dtype: str

In [14]:
# 8.Which city has  the highest population density ? 

df[df['population_density']==df['population_density'].max()]['city']

242    Örebro
Name: city, dtype: str

In [15]:
# 9. Which city has the lowest population density ?

df[df["population_density"]==df["population_density"].min()]["city"]

109    Mymensingh
Name: city, dtype: str

In [16]:
# 10 Which city has highest internet parcentage ? 

df[df['internet_pct']==df['internet_pct'].max()]['city']

4         Strasbourg
19              León
28            Tehran
35          Hamilton
63           Horsens
66          Mansoura
80          Zaragoza
91            Rhodes
106     Thessaloniki
115          Antwerp
123           Ashdod
132           Málaga
134        Maiduguri
154          Porirua
167           Moscow
178          Leipzig
220        Jyväskylä
229          Pereira
257           Bilbao
266           Quetta
268           Goyang
271           Poznań
283             Oulu
293       Lower Hutt
306          Kolding
310    Buon Ma Thuot
331          Pattaya
376           Bruges
380            Arica
396      Biel/Bienne
409            Hanoi
420           Madrid
424           Puebla
442        Groningen
446             Taif
450      Montpellier
494            Lahti
504           Bogotá
Name: city, dtype: str

In [17]:
df[df['internet_pct']==df['internet_pct'].max()]['city'].count()

np.int64(38)

In [18]:
# 11. Which city has the lowest internet percentage ? 

df[df['internet_pct']==df['internet_pct'].min()]['city']

402    Sandnes
Name: city, dtype: str

In [19]:
# 12.Which city has the highest electricity access ? 

df[df['electricity_access_pct']==df['electricity_access_pct'].max()]['city']

5         Tampines
30        Roskilde
35        Hamilton
37      St. Gallen
41           Plzeň
          ...
485      Nha Trang
489        Hamburg
493        Comilla
506    Fredrikstad
507        Bandung
Name: city, Length: 71, dtype: str

In [20]:
df[df['electricity_access_pct']==df['electricity_access_pct'].max()]['city'].count()

np.int64(71)

In [21]:
# 13.Which city has lowest electricity access ? 

df[df['electricity_access_pct']==df['electricity_access_pct'].min()]['city']

45    Volos
Name: city, dtype: str

In [22]:
# 14. Which city has the highest literacy rate ? 
df[df['literacy_pct']==df['literacy_pct'].max()]['city']

5           Tampines
14             Cairo
33            Cúcuta
62         Polokwane
106     Thessaloniki
143         Shenzhen
154          Porirua
320         Ioannina
323            Kalba
327             Bray
369            Kyoto
372    Umm Al Quwain
389         Fujairah
438           Lahore
459          Uppsala
461          Hougang
476             Pori
487            Urmia
Name: city, dtype: str

In [23]:
df[df['literacy_pct']==df['literacy_pct'].max()]['city'].count()

np.int64(18)

In [24]:
# 15. Which city has the lowest literacy rate

df[df['literacy_pct']==df['literacy_pct'].min()]['city']

405    Quebec City
Name: city, dtype: str

In [25]:
# 16. What are top 5 most populated cities? 

df.sort_values(by='population',ascending=False)[['city','country','population']].head()

          city         country  population
86     Ålesund          Norway   999999999
341    Tilburg     Netherlands    28885597
12      Ankara          Turkey    15391530
241    Kolkata           India    13529932
87   Sheffield  United Kingdom    13027880

In [26]:
# 17. what are the 5 least populated cities ? 

df.sort_values(by='population')[['city','country','population']].head()

          city   country  population
33      Cúcuta  Colombia         120
30    Roskilde   Denmark       50000
356  Ahmedabad     India       62036
63     Horsens   Denmark       64177
323      Kalba       UAE       83047

In [27]:
# 18. What are top 5 cities by population density ? 

df.sort_values(by='population_density',ascending=False)[['city','country','population_density']].head()

        city         country population_density
242   Örebro          Sweden            unknown
128  Chengdu           China            9992.57
172  Glasgow  United Kingdom            9984.33
419    Porto        Portugal            9954.47
267    Karaj            Iran            9939.26

In [28]:
# 19 What are the top 5 cities by city score ? 

df.sort_values(by='city_score',ascending=False)[['city','country','city_score']].head()

         city    country  city_score
83   Santiago      Chile       81.33
139    Sydney  Australia       77.75
324     Bursa     Turkey       77.61
343  Peshawar   Pakistan       77.51
414  San Juan  Argentina       77.14

In [29]:
# 20. What are the 5 cities with the lowest city score? 

df.sort_values(by='city_score')[['city','country','city_score']].head()

                 city      country  city_score
496          Adelaide    Australia       41.74
93      Kota Kinabalu     Malaysia       45.77
10   Shubra El Kheima        Egypt       45.90
197  Shubra El Kheima        Egypt       45.90
391    Zamboanga City  Philippines       46.44

In [30]:
# 21 What are the top 5 cities by average income ? 

df.sort_values(by='avg_income_usd',ascending=False)[['city','country','avg_income_usd']].head()

                  city      country  avg_income_usd
379             Lugano  Switzerland       150000.00
60             Halifax       Canada       125593.39
269             Napier  New Zealand       107482.07
219      Rostov-on-Don       Russia        99886.46
457  Nakhon Ratchasima     Thailand        95826.43

In [31]:
# 22. What are the top 5 cities by tourism index ? 

df.sort_values(by='tourism_index',ascending=False)[['city','country','tourism_index']].head()

            city   country  tourism_index
2    Johor Bahru  Malaysia          100.0
18         Surat     India          100.0
308        Konya    Turkey          100.0
90      Huancayo      Peru          100.0
309        Palma     Spain          100.0

In [32]:
# 23. Waht are the top 5 cities by green_space parcentage ? 

df.sort_values(by='green_space_pct',ascending=False)[['city','green_space_pct']].head()

          city  green_space_pct
144  San Diego            71.30
85        Cali            67.13
497     Swords            64.34
126       Zlín            64.21
50       Luxor            63.68

In [33]:
# 24. What are the top 5 cities by public - transport percentage ? 

df.sort_values(by='public_transport_pct',ascending=False)[['city','public_transport_pct']].head()

                 city  public_transport_pct
479           Aalborg                 100.0
478       Bucaramanga                 100.0
48   Ho Chi Minh City                 100.0
366          Trujillo                 100.0
204            Tabriz                 100.0

In [34]:
# 25. What are the 5 cities with the lowest crime rate ? 

df.sort_values(by='crime_rate')[['city','crime_rate']].head()

           city  crime_rate
439   Bnei Brak        -5.0
58     Arequipa         5.0
109  Mymensingh         5.0
73    Frankfurt         5.0
314     Wrocław         5.0

In [35]:
# 26. How many unique countries are there ? 

df['country'].nunique()

50

In [36]:
# 27. How many unique states/regions are there ? 

df['state'].nunique()

383

In [37]:
# 28. How many unique continents are there ? 

df['continent'].nunique()

6

In [38]:
# 29. Which continent has the most cities ? 

df['continent'].value_counts().head(1)

continent
Europe    205
Name: count, dtype: int64

In [39]:
# 30. How many cities are there in each continent ?
df['continent'].value_counts()

continent
Europe           205
Asia             161
South America     60
Africa            32
North America     30
Oceania           20
Name: count, dtype: int64

In [40]:
# 31.Which country has the most cities in the dataset ?

df['country'].value_counts().head(1)

country
Switzerland    12
Name: count, dtype: int64

In [41]:
# 32. How many cities belongs to India ?

df[df['country']=='India']['city'].count()

np.int64(10)

In [42]:
#33. List all indian cities

df[df['country']=='India']['city']

18         Surat
42     Bengaluru
59        Mumbai
156      Chennai
163    Hyderabad
174         Pune
241      Kolkata
356    Ahmedabad
388       Jaipur
426        Delhi
Name: city, dtype: str

In [43]:
# 34.List all cities in Europe

df[df['continent']=='Europe']['city']

3            Namur
4       Strasbourg
7            Genoa
12          Ankara
21         Setúbal
          ...
494          Lahti
497         Swords
501           Bari
505          Breda
506    Fredrikstad
Name: city, Length: 205, dtype: str

In [44]:
# 35. List all cities in in Asia

df[df['continent']=='Asia']['city']

1            Tabuk
2      Johor Bahru
5         Tampines
6        Cebu City
8           Sylhet
          ...
493        Comilla
495      Jerusalem
500       Shanghai
503      Palembang
507        Bandung
Name: city, Length: 161, dtype: str

In [45]:
# 36. List all cities in Africa

df[df['continent']=='Africa']['city']

0                 Asyut
9         Port Harcourt
10     Shubra El Kheima
14                Cairo
29            Nelspruit
32                 Giza
50                Luxor
55                Tanta
62            Polokwane
66             Mansoura
110                Suez
134           Maiduguri
189              Durban
190        Bloemfontein
197    Shubra El Kheima
199        Johannesburg
207    Pietermaritzburg
215           Port Said
264               Abuja
272              Ibadan
282          Benin City
284            Pretoria
287                 Aba
313               Lagos
315            Gqeberha
318              Kaduna
342           Cape Town
360         East London
386               Enugu
498                Kano
499       Port Harcourt
502          Alexandria
Name: city, dtype: str

In [46]:
# 37.List all cities in North-America 

df[df['continent']=='North America']['city']

19              León
35          Hamilton
60           Halifax
61       Los Angeles
71            Dallas
94          Edmonton
112     Philadelphia
116         San Jose
119    Ciudad Juárez
141          Zapopan
144        San Diego
160      San Antonio
188          Calgary
237           Cancún
251    New York City
274        Vancouver
335          Chicago
344      Guadalajara
352         Winnipeg
373          Toronto
393          Phoenix
405      Quebec City
415         Montreal
424           Puebla
432           Ottawa
441        Monterrey
445          Houston
458          Tijuana
460      Mexico City
469           Mérida
Name: city, dtype: str

In [47]:
# 38.List all cities in  South America

df[df['continent']=='South America']['city']

11               Antofagasta
17                 São Paulo
27                  Santa Fe
33                    Cúcuta
44                 Maracaibo
54                  Salvador
58                  Arequipa
76              Porto Alegre
82               Santa Marta
83                  Santiago
85                      Cali
90                  Huancayo
95                  Pucallpa
113                Cartagena
133               Valparaíso
136           Rio de Janeiro
140                Barcelona
169            Mar del Plata
177                 Curitiba
183    San Miguel de Tucumán
201                 Medellín
222                  Rosario
225           Ciudad Guayana
229                  Pereira
230                   Manaus
236             Puerto Montt
240                  Iquitos
250                 Rancagua
255                   Recife
258                  Córdoba
263                     Lima
277                 Valencia
279                  Maracay
281                    Talca
294                    Tacna
295                    Piura
319                   Temuco
329                La Serena
336           Belo Horizonte
353               Concepción
366                 Trujillo
370                 Brasília
371                    Salta
378             Buenos Aires
380                    Arica
392                  Caracas
400                   Ibagué
407                    Cusco
412             Barquisimeto
414                 San Juan
421                  Cabimas
433                Fortaleza
435                  Mendoza
443                 La Plata
449             Barranquilla
454                  Maturín
478              Bucaramanga
482                 Chiclayo
486           Puerto La Cruz
504                   Bogotá
Name: city, dtype: str

In [48]:
#39.List all cities in oceania 

df[df['continent']=='Oceania']['city']

15         Christchurch
22              Dunedin
52            Melbourne
139              Sydney
154             Porirua
161            Auckland
179            Tauranga
195          Wollongong
218    Palmerston North
234            Hamilton
269              Napier
286             Geelong
293          Lower Hutt
362               Perth
367            Canberra
390          Wellington
399          Gold Coast
406            Brisbane
418           Newcastle
496            Adelaide
Name: city, dtype: str

In [49]:
# 40.What country has the largest number of cities ?

df['country'].value_counts().idxmax()

'Switzerland'

In [50]:
# 41.Which Asian city has the highest population 

asia_df = df[df['continent']=='Asia']
asia_df[asia_df['population']==asia_df['population'].max()]['city']

241    Kolkata
Name: city, dtype: str

In [51]:
# 42. Which Europen city has the highest population ?abs


europe_df=df[df['continent']=='Europe']
europe_df[europe_df['population']==europe_df['population'].max()]['city']

86    Ålesund
Name: city, dtype: str

In [52]:
# 43. Which African city has the highest population ? 

africa_df = df[df['continent']=='Africa']
africa_df[africa_df['population']==africa_df['population'].max()]['city']

190    Bloemfontein
Name: city, dtype: str

In [53]:
# 44. Which North American city has the hieghest population ? 

temp = df[df['continent']=='North America']
temp[temp['population']==temp['population'].max()]['city']

424    Puebla
Name: city, dtype: str

In [54]:
# 45.Which South American city has the highest population ? 
temp = df[df['continent']=='South America']
temp[temp['population']==temp['population'].max()]['city']

353    Concepción
Name: city, dtype: str

In [55]:
# 46. Which ocianian city has the highest population 

temp =df[df['continent']=='Oceania']
temp[temp['population']==temp['population'].max()]['city']

293    Lower Hutt
Name: city, dtype: str

In [56]:
#47. Which continent has the highest average city population 

df.groupby('continent')['population'].mean().idxmax()

'Europe'

In [57]:
# 48. Which continent has highest average city score 

df.groupby('continent')['city_score'].mean().idxmax()

'Europe'

In [58]:
# 49. Which continent has the highest average income ?

df.groupby('continent')['avg_income_usd'].mean().idxmax()

'North America'

In [59]:
# 50. Which continent has the lowest average crime rate ?

df.groupby('continent')['crime_rate'].mean().idxmin()

'North America'

In [60]:
# 51. What is the average population by country ? 

df.groupby('country')['population'].mean()

country
Argentina         2.194942e+06
Australia         1.047668e+06
Austria           1.266100e+06
Bangladesh        2.154974e+06
Belgium           1.070513e+06
Brazil            1.164022e+06
Canada            1.590076e+06
Chile             1.889037e+06
China             2.601683e+06
Colombia          2.266596e+06
Czechia           1.741578e+06
Denmark           1.637172e+06
Egypt             1.555468e+06
Finland           2.482353e+06
France            7.063814e+05
Germany           2.522101e+06
Greece            2.413630e+06
India             2.725082e+06
Indonesia         1.610414e+06
Iran              2.005576e+06
Ireland           1.619509e+06
Israel            2.408053e+06
Italy             2.098971e+06
Japan             1.193787e+06
Malaysia          1.380563e+06
Mexico            1.850862e+06
Netherlands       5.593819e+06
New Zealand       1.317846e+06
Nigeria           1.347462e+06
Norway            1.021564e+08
Pakistan          1.584084e+06
Peru              1.729191e+06
Philippines       1.528670e+06
Poland            1.464569e+06
Portugal          2.311181e+06
Russia            1.475863e+06
Saudi Arabia      1.052115e+06
Singapore         3.071114e+06
South Africa      1.582514e+06
South Korea       1.491018e+06
Spain             8.947554e+05
Sweden            8.868998e+05
Switzerland       9.743999e+05
Thailand          2.281255e+06
Turkey            2.974219e+06
UAE               1.419625e+06
USA               1.996028e+06
United Kingdom    2.725443e+06
Venezuela         1.611669e+06
Vietnam           3.024616e+06
Name: population, dtype: float64

In [61]:
# 52. What is the average population by continent ?

df.groupby('continent')['population'].mean()

continent
Africa           1.492418e+06
Asia             1.968551e+06
Europe           6.812619e+06
North America    1.812322e+06
Oceania          1.182757e+06
South America    1.809243e+06
Name: population, dtype: float64

In [62]:
 # 53. What is the average city score by continent 

df.groupby('continent')['city_score'].mean()

continent
Africa           61.386563
Asia             61.964161
Europe           62.461707
North America    61.786333
Oceania          59.728000
South America    62.262167
Name: city_score, dtype: float64

In [63]:
# 54. What is the average income by continent 

df.groupby('continent')['avg_income_usd'].mean()

continent
Africa           35381.778000
Asia             33121.908077
Europe           35650.854800
North America    37099.515667
Oceania          36037.006316
South America    32302.143667
Name: avg_income_usd, dtype: float64

In [64]:
# 55. Waht is the average crime rate by continent 

df.groupby('continent')['crime_rate'].mean()

continent
Africa           43.478437
Asia             37.745155
Europe           36.768146
North America    36.730000
Oceania          87.707000
South America    40.686167
Name: crime_rate, dtype: float64

In [65]:
# 56.What is the average ait-quality index by continent 

df.groupby('continent')['air_quality_index'].mean()

continent
Africa           92.022581
Asia             85.910127
Europe           86.735678
North America    74.832143
Oceania          79.500000
South America    89.014035
Name: air_quality_index, dtype: float64

In [66]:
# 57. Which continent has the highest average income 

df.groupby('continent')['avg_income_usd'].mean().idxmax()

'North America'

In [ ]:
# 58.which